/**
 * ARTIFICE / ATLAS — EDIT THE RESEARCH INVENTORY HERE.
 *
 * Place IDs must stay unique. WGS84 coordinates are always [longitude, latitude].
 * "condition" preserves provisional notes from Yasmine's research table; these are
 * NOT independently verified current closure or demolition announcements.
 * "coordinateSource" documents where an actual location was checked.
 * "locationNote" flags provisional matches when the table names a district rather
 * than a single identifiable building.
 * Upload your own photographs to assets/places/<id>/, then add filenames to images.
 */

export const CATEGORIES = [
  { id: "shopping-mall", label: "Shopping mall" },
  { id: "department-store", label: "Department store" },
  { id: "cinema-complex", label: "Cinema complex" },
  { id: "amusement-park", label: "Amusement park" },
  { id: "electronics-complex", label: "Electronics complex" },
  { id: "mixed-use-complex", label: "Mixed-use complex" },
  { id: "new-town", label: "New town" },
  { id: "hotel", label: "Hotel" },
  { id: "airport", label: "Airport" },
  { id: "car-park", label: "Car park" },
  { id: "residential-complex", label: "Residential complex" },
  { id: "leisure-resort", label: "Leisure resort" },
  { id: "transport-infrastructure", label: "Transport infrastructure" },
  { id: "public-park", label: "Public park" },
  { id: "museum", label: "Museum / memorial" },
  { id: "other", label: "Other" }
];

export const TAG_LABELS = {
  "adaptive-reuse": "Adaptive reuse",
  "consumerism": "Consumerism",
  "electronics": "Electronics",
  "masterplanning": "Masterplanning",
  "periphery": "Periphery",
  "residential": "Residential",
  "retail": "Retail",
  "subculture": "Subculture",
  "technology": "Technology",
  "fashion": "Fashion",
  "commercial-decline": "Commercial decline",
  "mixed-program": "Mixed programme",
  "cultural-program": "Cultural programme",
  "transit-oriented": "Transit-oriented",
  "1970s": "1970s",
  "commercial-obsolescence": "Commercial obsolescence",
  "urban-memory": "Urban memory",
  "artificial-worlds": "Artificial worlds",
  "architectures-of-prosperity": "Architectures of prosperity",
  "suspended-time": "Suspended time",
  "ordinary-heritage": "Ordinary heritage",
  "afterlives": "Afterlives",
  "postmodernism": "Postmodernism",
  "leisure": "Leisure",
  "infrastructure": "Infrastructure",
  "tourism": "Tourism",
  "themed-environment": "Themed environment",
  "industrial-memory": "Industrial memory",
  "artificial-island": "Artificial island",
  "adaptive-landscape": "Adaptive landscape",
  "heritage-conservation": "Heritage conservation",
  "demolished": "Demolished",
  "speculative-futures": "Speculative futures",
  "urban-experiment": "Urban experiment",
  "public-space": "Public space",
  "mass-tourism": "Mass tourism",
  "memorial": "Memorial",
  "historic-site": "Historic site",
  "water-infrastructure": "Water infrastructure",
  "railway": "Railway",
  "vacation-housing": "Holiday housing",
  "reconversion": "Reconversion"
};

export const seedPlaces = [
  // FRANCE — existing places completed with the working inventory.
  {
    id: "maine-montparnasse",
    name: "Centre commercial Maine–Montparnasse",
    city: "Paris", country: "France",
    coordinates: [2.3211, 48.8423],
    category: "shopping-mall", tags: ["retail", "adaptive-reuse", "1970s"],

    description: "The Maine–Montparnasse retail complex is the site of ARTIFICE's La machine du dialogue project.",
    project: "projects.html?project=la-machine-du-dialogue",
    images: [
      { src: "assets/places/maine-montparnasse/01.webp", caption: "Existing interior passage", alt: "Interior of the Maine–Montparnasse shopping centre" },
      { src: "assets/places/maine-montparnasse/02.webp", caption: "Existing commercial interior", alt: "Vacant interior of the Maine–Montparnasse shopping centre" }
    ,
      { src: "assets/places/maine-montparnasse/08.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" },
      { src: "assets/places/maine-montparnasse/09.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" },
      { src: "assets/places/maine-montparnasse/10.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" },
      { src: "assets/places/maine-montparnasse/11.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" },
      { src: "assets/places/maine-montparnasse/12.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" },
      { src: "assets/places/maine-montparnasse/13.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" },
      { src: "assets/places/maine-montparnasse/14.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" },
      { src: "assets/places/maine-montparnasse/15.JPG", caption: "Centre commercial Maine–Montparnasse", alt: "Photograph of Centre commercial Maine–Montparnasse" }
    ],
    year: "1973",
    program: "Shops, offices and public facilities",
    condition: "Yasmine field inventory (Oct 2026): Centre closed to the public in 2026 according to the field inventory; basement sports facilities remain in use.",
    areaReliability: "High",
    area: "35,500 m² shopping centre",
    areaSource: "https://www.drieat.ile-de-france.developpement-durable.gouv.fr/IMG/pdf/190123_mrae_avis_sur_projet_rehabilitation_et_extension_tour_montparnasse_75_delibere.pdf",
    areaNote: "Commercial centre only, not the entire Maine–Montparnasse complex",
  },
  {
    id: "le-millenaire",
    images: [
      { src: "assets/places/le-millenaire/01.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/02.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/03.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/04.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/05.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/06.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/07.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/08.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/09.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" },
      { src: "assets/places/le-millenaire/10.jpeg", caption: "Le Millénaire", alt: "Photograph of Le Millénaire" }
    ],
    name: "Le Millénaire", city: "Aubervilliers", country: "France",
    coordinates: [2.382, 48.900],
    category: "shopping-mall", tags: ["retail", "periphery", "commercial-decline"],


    description: "Shopping-centre and office development in Aubervilliers on the northern edge of Paris.",
    year: "2011",
    program: "Shops and offices",
    condition: "Yasmine field inventory (Oct 2026): Field observation: severe retail decline and departed major franchises.",
    areaReliability: "Original",
    area: "56,000 m² retail; 17,000 m² offices",
  },
  {
    id: "bercy-2",
    images: [
      { src: "assets/places/bercy-2/01.JPG", caption: "Bercy 2", alt: "Photograph of Bercy 2" },
      { src: "assets/places/bercy-2/02.JPG", caption: "Bercy 2", alt: "Photograph of Bercy 2" },
      { src: "assets/places/bercy-2/03.JPG", caption: "Bercy 2", alt: "Photograph of Bercy 2" },
      { src: "assets/places/bercy-2/04.JPG", caption: "Bercy 2", alt: "Photograph of Bercy 2" },
      { src: "assets/places/bercy-2/05.JPG", caption: "Bercy 2", alt: "Photograph of Bercy 2" },
      { src: "assets/places/bercy-2/06.JPG", caption: "Bercy 2", alt: "Photograph of Bercy 2" }
    ],
    name: "Bercy 2", city: "Charenton-le-Pont", country: "France",
    coordinates: [2.405, 48.823],
    category: "shopping-mall", tags: ["retail", "periphery", "commercial-decline"],


    description: "Shopping centre by Renzo Piano Building Workshop at the edge of Paris.",
    year: "1990",
    program: "Shops",
    condition: "Yasmine field inventory (Oct 2026): Field observation: partly repurposed upper floor; proposed redevelopment, potential demolition in 2031 not confirmed.",
    areaReliability: "Original",
    area: "36,000 m² retail",
  },
  {
    id: "la-vache-noire",
    images: [
      { src: "assets/places/la-vache-noire/01.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/02.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/03.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/04.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/05.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/06.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/07.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/08.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/09.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" },
      { src: "assets/places/la-vache-noire/10.JPG", caption: "La Vache Noire", alt: "Photograph of La Vache Noire" }
    ],
    name: "La Vache Noire", city: "Arcueil", country: "France",
    coordinates: [2.32885, 48.81135],
    coordinateSource: "https://mapcarta.com/W62643138",
    category: "shopping-mall", tags: ["retail", "periphery", "commercial-decline"],


    description: "Shopping centre in Arcueil with a publicly accessible rooftop landscape.",
    year: "2007",
    program: "Shops",
    condition: "Yasmine field inventory (Oct 2026): Field observation: gradual commercial decline and vacant units.",
    areaReliability: "Original",
    area: "49,263 m²",
  },
  {
    id: "belle-epine",
    images: [
      { src: "assets/places/belle-epine/01.jpeg", caption: "Belle Épine", alt: "Photograph of Belle Épine" },
      { src: "assets/places/belle-epine/02.jpeg", caption: "Belle Épine", alt: "Photograph of Belle Épine" },
      { src: "assets/places/belle-epine/03.jpeg", caption: "Belle Épine", alt: "Photograph of Belle Épine" },
      { src: "assets/places/belle-epine/04.jpeg", caption: "Belle Épine", alt: "Photograph of Belle Épine" },
      { src: "assets/places/belle-epine/05.jpeg", caption: "Belle Épine", alt: "Photograph of Belle Épine" },
      { src: "assets/places/belle-epine/06.jpeg", caption: "Belle Épine", alt: "Photograph of Belle Épine" },
      { src: "assets/places/belle-epine/07.jpeg", caption: "Belle Épine", alt: "Photograph of Belle Épine" }
    ],
    name: "Belle Épine", city: "Thiais", country: "France",
    coordinates: [2.37214, 48.75659],
    coordinateSource: "https://mapcarta.com/W263891555",
    category: "shopping-mall", tags: ["retail", "periphery", "1970s"],


    description: "A major early regional shopping centre in Thiais, southeast of Paris.",
    year: "1971",
    program: "Shops and cinema",
    condition: "Yasmine field inventory (Oct 2026): Field observation: renewed activity associated with transport and projects in surrounding area.",
    areaReliability: "Original",
    area: "140,000 m²",
  },

  // ALGERIA
  {
    id: "riadh-el-feth",
    name: "Riadh El Feth", city: "Algiers", country: "Algeria",
    coordinates: [3.07025, 36.74326],
    coordinateSource: "https://mapcarta.com/fr/W1271733343",
    category: "mixed-use-complex", tags: ["retail", "cultural-program", "mixed-program"],

    description: "Post-independence commercial and cultural complex at El Madania, inaugurated in the mid-1980s.",
    year: "1982 (construction began)",
    program: "Shops, cultural facilities and leisure",
    condition: "Yasmine field inventory (Oct 2026): Field observation: largely underused commercial and cultural complex.",
    areaReliability: "Pending",
  },

  // SOUTH KOREA
  {
    id: "yongsan-et-land",
    name: "Yongsan ET Land", city: "Seoul", country: "South Korea",
    coordinates: [126.9595403701, 37.5327661639],
    coordinateSource: "https://data.visitkorea.or.kr/resource/132229",
    category: "electronics-complex", tags: ["retail", "electronics", "technology"],
    description: "Electronics retail complex in Yongsan, opened in 1988 as part of the district's development as a major electronics trading area.",
    year: "1988",
    program: "Electronics, computers, audio equipment, cameras and related retail",
    source: "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=103977",
  },
  {
    id: "techno-mart",
    name: "Gangbyeon Techno Mart", city: "Seoul", country: "South Korea",
    coordinates: [127.0957, 37.5355],
    category: "electronics-complex", tags: ["retail", "electronics", "technology"],

    description: "Large electronics and entertainment retail complex near Gangbyeon Station.",
    year: "1998",
    program: "Electronics retail, shops, cinema and offices",
    condition: "Yasmine field inventory (Oct 2026): Field observation: vacant shops, informal retail appearance and reuse of two floors for weddings.",
    areaReliability: "High",
    area: "≈260,000 m² total GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20110705141100004",
    areaNote: "Total GFA includes offices and other facilities",
    images: [{"src":"assets/places/techno-mart/DSC01729.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01735.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01766.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01776.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01780.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},
      { src: "assets/places/techno-mart/01.jpeg", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/02.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/03.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/04.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/05.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/06.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/07.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/08.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/09.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/10.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/11.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/12.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/13.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/14.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/15.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" },
      { src: "assets/places/techno-mart/16.JPG", caption: "Gangbyeon Techno Mart", alt: "Photograph of Gangbyeon Techno Mart" }
    ],
  },
  {
    id: "venezia-mega-mall",
    name: "Venezia Mega Mall", city: "Seoul", country: "South Korea",
    coordinates: [127.021434, 37.570978],
    coordinateSource: "https://lse.purpleo.kr/article/1415",
    locationNote: "Approximately located from a commercial registry at 400 Cheonggyecheon-ro. Building footprint should be checked.",
    category: "shopping-mall", tags: ["retail", "mixed-program"],
    description: "Shopping complex at 400 Cheonggyecheon-ro, Hwanghak-dong, Seoul.",
    year: "2008",
    program: "Shopping and leisure within residential complex",
    condition: "Yasmine field inventory (Oct 2026): Field observation: space mostly used for online retail trade, with underused upper levels.",
    areaReliability: "High",
    area: "≈130,000 m² mall GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20110614058700003",
    areaNote: "Retail and leisure areas, not residential towers",
  },
  {
    id: "migliore-dongdaemun",
    images: [
      { src: "assets/places/migliore-dongdaemun/DSC00368.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00371.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00380.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00382.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00385.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00513.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00520.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00521.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00529.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00531.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00535.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00536.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00539.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00544.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" },
      { src: "assets/places/migliore-dongdaemun/DSC00553.JPG", caption: "Migliore Dongdaemun", alt: "Photograph of Migliore Dongdaemun" }
    ],
    name: "Migliore Dongdaemun", city: "Seoul", country: "South Korea",
    coordinates: [127.008527, 37.567963],
    coordinateSource: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?menuSn=315&vcontsId=106366",
    locationNote: "The inventory says 'Migliore'. This pin identifies the Dongdaemun branch; confirm it is the intended one.",
    category: "shopping-mall", tags: ["retail", "fashion"],
    description: "Multi-storey fashion retail complex in the Dongdaemun district.",
    year: "1998",
    program: "Vertical fashion retail",
    condition: "Yasmine field inventory (Oct 2026): Field observation: some vacant floors and declining commercial activity.",
    areaReliability: "Medium",
    area: "49,566 m² total GFA",
    areaSource: "https://disco.re/l/ozcxwk",
    areaNote: "Whole building GFA",
  },
  {
    id: "apm-place",
    name: "apM PLACE", city: "Seoul", country: "South Korea",
    coordinates: [127.00841, 37.5653],
    coordinateSource: "https://mapcarta.com/W400847801",
    category: "shopping-mall", tags: ["retail", "fashion"],
    description: "Multi-storey fashion wholesale and shopping complex at Eulji-ro 276, Dongdaemun.",
    year: "2016",
    program: "Wholesale fashion and vertical retail",
    condition: "Yasmine field inventory (Oct 2026): Field observation: vacancies in a wholesale centre.",
    areaReliability: "Pending",
  },
  {
    id: "hapjeong-mall",
    images: [
      { src: "assets/places/hapjeong-mall/01.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" },
      { src: "assets/places/hapjeong-mall/02.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" },
      { src: "assets/places/hapjeong-mall/03.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" },
      { src: "assets/places/hapjeong-mall/04.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" },
      { src: "assets/places/hapjeong-mall/05.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" },
      { src: "assets/places/hapjeong-mall/06.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" },
      { src: "assets/places/hapjeong-mall/07.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" },
      { src: "assets/places/hapjeong-mall/08.JPG", caption: "Hapjeong Mall / Mecenatpolis (provisional)", alt: "Photograph of Hapjeong Mall / Mecenatpolis (provisional)" }
    ],
    name: "Hapjeong Mall / Mecenatpolis (provisional)", city: "Seoul", country: "South Korea",
    coordinates: [126.91378, 37.55089],
    coordinateSource: "https://mapcarta.com/W306956698",
    locationNote: "The inventory only says 'Hapjeong mall'. Mapped provisionally to Mecenatpolis; please confirm the intended building.",
    category: "shopping-mall", tags: ["retail", "mixed-program", "transit-oriented"],
    description: "Shopping and mixed-use complex at Hapjeong Station, provisionally identified with Mecenatpolis.",
    year: "2012",
    program: "Shopping within residential complex",
    condition: "Yasmine field inventory (Oct 2026): Field observation: active centre with vacant basement and upper-floor units.",
    areaReliability: "High",
    area: "40,176 m² mall GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20120312093300003",
    areaNote: "Mall only, excluding residential towers",
  },
  {
    id: "goodmorning-city",
    name: "Goodmorning City", city: "Seoul", country: "South Korea",
    coordinates: [127.0075, 37.56668],
    coordinateSource: "https://mapcarta.com/W358284628",
    category: "shopping-mall", tags: ["retail", "fashion"],
    description: "Multi-storey commercial complex in Seoul's Dongdaemun district.",
    year: "2008",
    program: "Fashion retail and leisure facilities",
    condition: "Yasmine field inventory (Oct 2026): Field observation: spa open, cinema reportedly closed September 2026, multiple vacancies.",
    areaReliability: "High",
    area: "92,206 m² total GFA",
    areaSource: "https://m.apparelnews.co.kr/news/news_view/?idx=130709",
    areaNote: "Includes commercial, leisure and office floors",
  },
  {
    id: "wangsimni-bitplex",
    images: [
      { src: "assets/places/wangsimni-bitplex/01.JPG", caption: "Wangsimni / Bitplex (provisional)", alt: "Photograph of Wangsimni / Bitplex (provisional)" },
      { src: "assets/places/wangsimni-bitplex/02.JPG", caption: "Wangsimni / Bitplex (provisional)", alt: "Photograph of Wangsimni / Bitplex (provisional)" },
      { src: "assets/places/wangsimni-bitplex/03.JPG", caption: "Wangsimni / Bitplex (provisional)", alt: "Photograph of Wangsimni / Bitplex (provisional)" },
      { src: "assets/places/wangsimni-bitplex/04.JPG", caption: "Wangsimni / Bitplex (provisional)", alt: "Photograph of Wangsimni / Bitplex (provisional)" },
      { src: "assets/places/wangsimni-bitplex/05.JPG", caption: "Wangsimni / Bitplex (provisional)", alt: "Photograph of Wangsimni / Bitplex (provisional)" },
      { src: "assets/places/wangsimni-bitplex/06.JPG", caption: "Wangsimni / Bitplex (provisional)", alt: "Photograph of Wangsimni / Bitplex (provisional)" },
      { src: "assets/places/wangsimni-bitplex/07.jpeg", caption: "Wangsimni / Bitplex (provisional)", alt: "Photograph of Wangsimni / Bitplex (provisional)" }
    ],
    name: "Wangsimni / Bitplex (provisional)", city: "Seoul", country: "South Korea",
    coordinates: [127.0383, 37.56212],
    coordinateSource: "https://mapcarta.com/W1258207418",
    locationNote: "The inventory only says 'Wangsimni'. Mapped provisionally to the Bitplex / Enter-6 complex at Wangsimni Station.",
    category: "mixed-use-complex", tags: ["retail", "mixed-program", "transit-oriented"],
    description: "Shopping and entertainment complex integrated with Wangsimni Station.",
    year: "2008",
    program: "Rail station, shops, cinema and leisure",
    condition: "Yasmine field inventory (Oct 2026): Field observation: active station-linked centre with less-used aisles.",
    areaReliability: "High",
    area: "≈99,000 m² total GFA",
    areaSource: "https://fi.co.kr/mobile/view.asp?idx=40956",
    areaNote: "Station and mixed-use complex",
  },

  // FOUR ADDITIONAL SITES IN JAPAN, SOUTH KOREA, HONG KONG AND TAIWAN.
  {
    id: "aeon-sanda-woody-town",
    name: "AEON Sanda Woody Town",
    city: "Sanda", country: "Japan",
    coordinates: [135.18746, 34.90853],
    coordinateSource: "https://mapcarta.com/W506631400",
    category: "shopping-mall",
    tags: ["retail", "cultural-program"],

    description: "Shopping complex in Sanda Woody Town, Hyogo Prefecture, with a multi-screen cinema. It forms part of the commercial centre of a planned suburban community.",
    year: "2000",
    program: "Shops, cinema and suburban centre",
    condition: "Yasmine field inventory (Oct 2026): Former Saty shopping centre.",
    areaReliability: "High",
    area: "25,298 m² retail",
    areaSource: "https://www.jcsc.or.jp/data/pdf/2019list_of_shopping_centers.pdf",
    areaNote: "Retail area only",
  },
  {
    id: "time-terrace-dongtan",
    name: "Time Terrace Dongtan",
    city: "Hwaseong", country: "South Korea",
    coordinates: [127.069312, 37.204856],
    coordinateSource: "https://bim.purpleo.kr/article/1297",
    locationNote: "Interpreted from 'Times Square in Dongtan'. This is the Time Terrace mall inside Metapolis, operated by the company behind Seoul Times Square. It is not the unrelated SH Times Square industrial building.",
    category: "shopping-mall",
    tags: ["retail", "consumerism", "mixed-program", "commercial-obsolescence"],

    description: "Shopping centre within Dongtan's Metapolis residential and commercial complex. Formerly Center Point Mall, the retail spaces were relaunched as Time Terrace in 2022.",
    source: "https://view.asiae.co.kr/en/article/2022031709305224800",
    year: "2022 (renovation)",
    program: "Shops, cinema and restaurants",
    condition: "Yasmine field inventory (Oct 2026): Former Center Point Mall, relaunched as Time Terrace in 2022.",
    areaReliability: "High",
    area: "≈142,000 m² total GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20220317039800003",
    areaNote: "Commercial blocks A and B",
  },
  {
    id: "moko-mong-kok-east",
    name: "MOKO (Grand Century Place)",
    city: "Hong Kong", country: "Hong Kong",
    coordinates: [114.17238, 22.32318],
    coordinateSource: "https://mapcarta.com/W37517528",
    locationNote: "Interpreted from 'Mong Kok East'. This is MOKO, the shopping mall beside Mong Kok East station.",
    category: "shopping-mall",
    tags: ["retail", "mixed-program", "transit-oriented"],

    description: "Multi-level shopping complex connected to Mong Kok East station, integrated with offices and the Royal Plaza Hotel.",
    source: "https://www.wikidata.org/wiki/Q11080935",
    year: "1997",
    program: "Shops, hotel, offices and station access",
    condition: "Yasmine field inventory (Oct 2026): Shopping complex linked to Mong Kok East.",
    areaReliability: "Medium",
    area: "≈67,000 m² retail GFA",
    areaSource: "https://www.luxstate.com/hk-retail/mall/kowloon/moko/",
    areaNote: "Mall only",
  },
  {
    id: "qianyue-building",
    name: "Qianyue Building (千越大樓)",
    city: "Taichung", country: "Taiwan",
    coordinates: [120.68314, 24.13827],
    coordinateSource: "https://explander.com/east-central-asia/taiwan/taichung/qianyue-building-taichung-taiwan/",
    category: "mixed-use-complex",
    tags: ["retail", "commercial-obsolescence", "urban-memory", "adaptive-reuse", "1970s"],

    description: "An ageing mixed-use commercial building near Taichung Station, known for its former rooftop restaurant and its partial reuse by artists during the Escape Plan X initiative.",
    source: "https://www.taipeitimes.com/News/feat/archives/2025/05/13/2003836777",
    year: "1970s",
    program: "Former department store, restaurants, bars and housing",
    condition: "Yasmine field inventory (Oct 2026): Field observation: former retail space marked by fire in 2005 and artist interventions.",
    areaReliability: "Medium",
    area: "21,070 m² total GFA",
    areaSource: "https://taichung2050.pixnet.net/blog/posts/10342072765",
    areaNote: "Building GFA",
  },

  // ADDITIONAL ARTIFICE RESEARCH PLACES (already on the Atlas; preserved)
  {
    id: "dongtan",
    name: "Dongtan New Town", city: "Hwaseong", country: "South Korea",
    coordinates: [127.071, 37.206],
    category: "new-town", tags: ["masterplanning", "consumerism", "residential"],
    description: "A planned new town whose apartment brands, infrastructure and corporate economies offer a lens onto contemporary urban consumption.",
    year: "2007 (phase 1)",
    program: "New town, housing and commerce",
    condition: "Yasmine field inventory (Oct 2026): Planned new town; area is land, not floor area.",
    areaReliability: "High",
    area: "9,035,000 m² development land (Dongtan 1)",
    areaSource: "https://www.molit.go.kr/USR/policyData/m_34681/dtl.jsp?id=524&lcmspage=29",
    areaNote: "Dongtan 1 development land, not building area",
  },
  {
    id: "nakano-broadway",
    name: "Nakano Broadway", city: "Tokyo", country: "Japan",
    coordinates: [139.6658, 35.7092],
    category: "mixed-use-complex", tags: ["retail", "subculture"],
    description: "A multi-storey shopping complex that evolved into a dense ecosystem of specialist retail and subcultures.",
    images: [{ src: "assets/places/nakano-broadway/DSC01831.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/01.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/02.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/03.jpeg", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/04.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/05.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/06.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/07.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/08.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/09.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/10.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/11.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/12.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" },
      { src: "assets/places/nakano-broadway/13.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" }
    ],
    year: "1966",
    program: "Shops, apartments and specialist retailers",
    condition: "Yasmine field inventory (Oct 2026): Field observation: commercial gallery specialising increasingly in collectibles and subculture.",
    areaReliability: "Medium",
    area: "≈53,366 m² main building GFA",
    areaSource: "https://skyscraperclub.com/?p=16733",
    areaNote: "Main building only",
  },
  {
    id: "times-square-seoul",
    name: "Times Square Yeongdeungpo",
    city: "Seoul",
    country: "South Korea",
    coordinates: [126.90402,37.51709],
    coordinateSource: "https://mapcarta.com/W344430230",
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, hotel, cinema and offices",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "High",
    description: "Shops, hotel, cinema and offices in Seoul",
    area: "376,400 m² total GFA; 126,800 m² retail",
    areaSource: "https://www.hankyung.com/article/2009090366231",
    areaNote: "Mixed-use GFA includes non-retail area",
  },
  {
    id: "art-forest",
    images: [
      { src: "assets/places/art-forest/01.JPG", caption: "Art Forest", alt: "Photograph of Art Forest" },
      { src: "assets/places/art-forest/1.JPG", caption: "Art Forest", alt: "Photograph of Art Forest" },
      { src: "assets/places/art-forest/02.JPG", caption: "Art Forest", alt: "Photograph of Art Forest" },
      { src: "assets/places/art-forest/03.jpeg", caption: "Art Forest", alt: "Photograph of Art Forest" }
    ],
    name: "Art Forest",
    city: "Seoul",
    country: "South Korea",
    coordinates: null,
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and leisure",
    condition: "Yasmine field inventory (Oct 2026): New retail facility reported with vacant ground-floor units; exact location requires verification",
    areaReliability: "Pending",
    description: "Shops and leisure in Seoul"
  },
  {
    id: "euljiro-underground",
    images: [
      { src: "assets/places/euljiro-underground/01.JPG", caption: "Euljiro Underground Shopping Centre", alt: "Photograph of Euljiro Underground Shopping Centre" },
      { src: "assets/places/euljiro-underground/02.JPG", caption: "Euljiro Underground Shopping Centre", alt: "Photograph of Euljiro Underground Shopping Centre" },
      { src: "assets/places/euljiro-underground/03.jpeg", caption: "Euljiro Underground Shopping Centre", alt: "Photograph of Euljiro Underground Shopping Centre" },
      { src: "assets/places/euljiro-underground/04.jpeg", caption: "Euljiro Underground Shopping Centre", alt: "Photograph of Euljiro Underground Shopping Centre" }
    ],
    name: "Euljiro Underground Shopping Centre",
    city: "Seoul",
    country: "South Korea",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Underground shops and pedestrian passageways",
    condition: "Yasmine field inventory (Oct 2026): Field observation: underused underground commercial arcade",
    areaReliability: "High",
    description: "Underground shops and pedestrian passageways in Seoul",
    area: "20,334 m² arcade",
    areaSource: "https://www.sisul.or.kr/global/main/en/sub/shoppingcenter.jsp",
    areaNote: "Underground arcade, not adjacent centres",
  },
  {
    id: "lions-plaza",
    name: "Lions’ Plaza Commercial Building",
    city: "Taipei",
    country: "Taiwan",
    coordinates: null,
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and mixed-use spaces",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "Pending",
    description: "Shops and mixed-use spaces in Taipei"
  },
  {
    id: "sanchong-tang-city",
    name: "Sanchong Tang City Plaza",
    city: "New Taipei",
    country: "Taiwan",
    coordinates: null,
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and mixed-use spaces",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited; shopping centre coordinates require verification",
    areaReliability: "Pending",
    description: "Shops and mixed-use spaces in New Taipei"
  },
  {
    id: "new-shimbashi-building",
    images: [
      { src: "assets/places/new-shimbashi-building/01.JPG", caption: "New Shimbashi Building", alt: "Photograph of New Shimbashi Building" },
      { src: "assets/places/new-shimbashi-building/02.JPG", caption: "New Shimbashi Building", alt: "Photograph of New Shimbashi Building" },
      { src: "assets/places/new-shimbashi-building/03.JPG", caption: "New Shimbashi Building", alt: "Photograph of New Shimbashi Building" },
      { src: "assets/places/new-shimbashi-building/04.JPG", caption: "New Shimbashi Building", alt: "Photograph of New Shimbashi Building" },
      { src: "assets/places/new-shimbashi-building/05.JPG", caption: "New Shimbashi Building", alt: "Photograph of New Shimbashi Building" },
      { src: "assets/places/new-shimbashi-building/06.JPG", caption: "New Shimbashi Building", alt: "Photograph of New Shimbashi Building" },
      { src: "assets/places/new-shimbashi-building/07.JPG", caption: "New Shimbashi Building", alt: "Photograph of New Shimbashi Building" }
    ],
    name: "New Shimbashi Building",
    city: "Tokyo",
    country: "Japan",
    coordinates: [139.75736,35.66628],
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and offices",
    condition: "Yasmine field inventory (Oct 2026): Field observation: decline apparent on upper floors",
    areaReliability: "High",
    description: "Shops and offices in Tokyo",
    area: "58,107 m² total GFA",
    areaSource: "https://www.mhs.co.jp/work/new-shinbashi/",
    areaNote: "Whole building GFA",
  },
  {
    id: "asakusa-underground",
    images: [
      { src: "assets/places/asakusa-underground/01.JPG", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" },
      { src: "assets/places/asakusa-underground/02.JPG", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" },
      { src: "assets/places/asakusa-underground/03.JPG", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" },
      { src: "assets/places/asakusa-underground/04.JPG", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" },
      { src: "assets/places/asakusa-underground/05.jpeg", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" },
      { src: "assets/places/asakusa-underground/06.JPG", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" },
      { src: "assets/places/asakusa-underground/07.JPG", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" },
      { src: "assets/places/asakusa-underground/08.jpeg", caption: "Asakusa Underground Shopping Street", alt: "Photograph of Asakusa Underground Shopping Street" }
    ],
    name: "Asakusa Underground Shopping Street",
    city: "Tokyo",
    country: "Japan",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Underground shops and restaurants",
    condition: "Yasmine field inventory (Oct 2026): Established historic arcade, now visited for its retro character",
    areaReliability: "Pending",
    description: "Underground shops and restaurants in Tokyo"
  },
  {
    id: "aeon-laketown",
    name: "AEON LakeTown",
    city: "Koshigaya",
    country: "Japan",
    coordinates: [139.82611,35.87861],
    category: "shopping-mall",
    tags: ["retail"],
    program: "Large suburban shopping centre",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "High",
    description: "Large suburban shopping centre in Koshigaya",
    area: "≈403,000 m² total GFA; 190,000 m² leasable",
    areaSource: "https://www.aeonmall.com/news/index/13594/",
    areaNote: "Three Aeon complexes combined",
  },
  {
    id: "aeon-makuhari-new-city",
    name: "AEON MALL Makuhari New City",
    city: "Chiba",
    country: "Japan",
    coordinates: [140.02873,35.65469],
    coordinateSource: "https://mapcarta.com/W695894961",
    year: "2013",
    category: "shopping-mall",
    tags: ["retail"],
    program: "Large interconnected shopping centre",
    searchTerms: ["Makuhari Shintoshin", "AEON Mall Makuhari", "イオンモール幕張新都心", "AEON Mall Maluhari New City"],
    condition: "Yasmine field inventory (Oct 2026): Field observation: oversized facilities and areas with low use",
    areaReliability: "High",
    description: "Large interconnected shopping centre in Chiba",
    area: "≈402,000 m² total GFA; 128,000 m² leasable",
    areaSource: "https://www.aeonmall.com/facility/detail/1529/",
    areaNote: "GFA includes parking",
    source: "https://www.aeonmall.com/facility/detail/1529/1000/",
  },
  {
    id: "hatoya-hotel",
    name: "Hatoya Hotel",
    city: "Ito",
    country: "Japan",
    coordinates: null,
    category: "hotel",
    tags: ["retail"],
    program: "Hot spring hotel and leisure facilities",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "Pending",
    description: "Hot spring hotel and leisure facilities in Ito"
  },
  {
    id: "decks-tokyo-beach",
    images: [
      { src: "assets/places/decks-tokyo-beach/1.jpeg", caption: "DECKS Tokyo Beach", alt: "Photograph of DECKS Tokyo Beach" },
      { src: "assets/places/decks-tokyo-beach/02.jpeg", caption: "DECKS Tokyo Beach", alt: "Photograph of DECKS Tokyo Beach" },
      { src: "assets/places/decks-tokyo-beach/03.jpeg", caption: "DECKS Tokyo Beach", alt: "Photograph of DECKS Tokyo Beach" },
      { src: "assets/places/decks-tokyo-beach/04.jpeg", caption: "DECKS Tokyo Beach", alt: "Photograph of DECKS Tokyo Beach" },
      { src: "assets/places/decks-tokyo-beach/05.jpeg", caption: "DECKS Tokyo Beach", alt: "Photograph of DECKS Tokyo Beach" },
      { src: "assets/places/decks-tokyo-beach/06.jpeg", caption: "DECKS Tokyo Beach", alt: "Photograph of DECKS Tokyo Beach" },
      { src: "assets/places/decks-tokyo-beach/07.jpeg", caption: "DECKS Tokyo Beach", alt: "Photograph of DECKS Tokyo Beach" }
    ],
    name: "DECKS Tokyo Beach",
    city: "Tokyo",
    country: "Japan",
    coordinates: [139.7759,35.62906],
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, attractions and leisure",
    condition: "Yasmine field inventory (Oct 2026): Field observation: underused areas; Island Mall added 2000",
    areaReliability: "High",
    description: "Shops, attractions and leisure in Tokyo",
    area: "≈69,035 m² total GFA",
    areaSource: "https://www.tokyu-land.co.jp/urban/shopping/list/051.html",
    areaNote: "Total GFA",
  },
  {
    id: "divercity-tokyo-plaza",
    images: [
      { src: "assets/places/divercity-tokyo-plaza/01.JPG", caption: "DiverCity Tokyo Plaza", alt: "Photograph of DiverCity Tokyo Plaza" },
      { src: "assets/places/divercity-tokyo-plaza/02.JPG", caption: "DiverCity Tokyo Plaza", alt: "Photograph of DiverCity Tokyo Plaza" },
      { src: "assets/places/divercity-tokyo-plaza/03.JPG", caption: "DiverCity Tokyo Plaza", alt: "Photograph of DiverCity Tokyo Plaza" },
      { src: "assets/places/divercity-tokyo-plaza/04.jpeg", caption: "DiverCity Tokyo Plaza", alt: "Photograph of DiverCity Tokyo Plaza" }
    ],
    name: "DiverCity Tokyo Plaza",
    city: "Tokyo",
    country: "Japan",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, restaurants and attractions",
    condition: "Yasmine field inventory (Oct 2026): Field observation: several large low-use areas",
    areaReliability: "High",
    description: "Shops, restaurants and attractions in Tokyo",
    area: "≈140,200 m² mall and parking GFA; 47,000 m² retail",
    areaSource: "https://www.mitsuifudosan.co.jp/corporate/news/2021/0412/",
    areaNote: "Mall and parking area",
  },
  {
    id: "aquacity-odaiba",
    name: "AQUA CiTY ODAIBA",
    city: "Tokyo",
    country: "Japan",
    coordinates: [139.77353,35.6278],
    coordinateSource: "https://mapcarta.com/W328162159",
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, restaurants and cinema",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "High",
    description: "Shops, restaurants and cinema in Tokyo",
    area: "≈94,000 m² total GFA; 42,500 m² retail",
    areaSource: "https://www.mec.co.jp/ir/library/2013/4Q/FACT%20BOOK%20201303.pdf",
    areaNote: "Mall GFA and retail area",
  },
  {
    id: "rakuseinu",
    name: "Rakuseinu / Rakusai Town Centre",
    city: "Kyoto",
    country: "Japan",
    coordinates: [135.67677,34.96212],
    coordinateSource: "https://mapcarta.com/N7321694978",
    category: "shopping-mall",
    tags: ["retail"],
    program: "New-town shopping arcade",
    condition: "Yasmine field inventory (Oct 2026): Field observation: ongoing reuse and vacant upper floor after adjoining store closure",
    areaReliability: "Medium",
    description: "New-town shopping arcade in Kyoto",
    area: "15,915 m² retail",
    areaSource: "https://toshoken.com/news/30550",
    areaNote: "Shopping arcade, not adjacent department store",
  },
  {
    id: "viking-line",
    name: "Viking Line Baltic Ferry",
    city: "Baltic Sea",
    country: "Multiple countries",
    coordinates: null,
    category: "other",
    tags: ["retail"],
    program: "Passenger ferry, retail and leisure",
    condition: "Yasmine field inventory (Oct 2026): Helsinki, Tallinn and Stockholm ferry routes; specify a vessel before geolocating",
    areaReliability: "Pending",
    description: "Passenger ferry, retail and leisure in Baltic Sea"
  },

  // EXPANDED ARTIFICIAL WORLDS: TOURISM, INFRASTRUCTURE, MEMORY AND URBAN EXPERIMENTS.
  {
    id: "spa-resort-hawaiians",
    name: "Spa Resort Hawaiians (Joban Hawaiian Center)",
    city: "Iwaki",
    country: "Japan",
    year: "1966 (opened)",
    clockYear: 1966,
    clockEvent: "Resort opened",
    coordinates: [140.8792,37.0514],
    coordinateSource: "https://www.hotspringsguides.com/hot-springs/spa-resort-hawaiians-japan",
    category: "leisure-resort",
    tags: ["artificial-worlds","architectures-of-prosperity","themed-environment","leisure","industrial-memory","reconversion","tourism"],
    program: "Tropical indoor water park, hot springs, hotel, theatre and leisure facilities",
    condition: "Operating resort. The original Joban Hawaiian Center has evolved through expansions and rebranding. The 1966 date refers to the initial opening, not the completion date of every current building.",
    description: "A tropical destination built above the thermal waters of a former coal-mining region. The artificial Hawaiian environment became a vehicle for regional economic conversion and an enduring vision of leisure.",
    source: "https://www.hawaiians.co.jp/en/corporate/history/",
    dateNote: "Opened on 15 November 1966 as Joban Hawaiian Center."
  },
  {
    id: "umihotaru-parking-area",
    name: "Umihotaru Parking Area",
    city: "Kisarazu, Tokyo Bay",
    country: "Japan",
    year: "1997 (opened)",
    clockYear: 1997,
    clockEvent: "Artificial island opened",
    coordinates: [139.87444,35.46444],
    coordinateSource: "https://www.wikidata.org/wiki/Q11151285",
    category: "transport-infrastructure",
    tags: ["artificial-worlds","suspended-time","infrastructure","artificial-island","leisure","tourism"],
    program: "Artificial island, motorway rest stop, observation decks, restaurants, retail and infrastructure",
    condition: "Active motorway facility; the time reference marks the 1997 opening of the Tokyo Bay Aqua-Line.",
    description: "An artificial island in Tokyo Bay at the interface between an underwater motorway tunnel and bridge, conceived as both transport infrastructure and a destination suspended in the sea.",
    source: "https://www.wikidata.org/wiki/Q11151285",
    dateNote: "Tokyo Bay Aqua-Line and Umihotaru began operation in December 1997."
  },
  {
    id: "tsukuba-center-building",
    name: "Tsukuba Center Building",
    city: "Tsukuba",
    country: "Japan",
    year: "1983 (completed)",
    clockYear: 1983,
    clockEvent: "Complex completed",
    coordinates: [140.114056,36.081944],
    coordinateSource: "https://www.wikidata.org/wiki/Q4448816",
    category: "mixed-use-complex",
    tags: ["postmodernism","architectures-of-prosperity","artificial-worlds","urban-experiment","public-space","technology"],
    program: "Public plaza, hotel, concert hall, offices and commercial facilities",
    condition: "Existing mixed-use civic complex, subject to successive changes in use and urban context.",
    description: "Arata Isozaki's postmodern civic ensemble for the planned science city of Tsukuba. Its sunken plaza stages an elaborate dialogue between historical fragments and technological futurism.",
    source: "https://isozaki.co.jp/archives/projects/%E3%81%A4%E3%81%8F%E3%81%B0%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%93%E3%83%AB/",
    dateNote: "Designed and built between 1979 and 1983; completion date used for the clock."
  },
  {
    id: "huis-ten-bosch",
    name: "Huis Ten Bosch",
    city: "Sasebo",
    country: "Japan",
    year: "1992 (opened)",
    clockYear: 1992,
    clockEvent: "Themed town opened",
    coordinates: [129.78886,33.08587],
    coordinateSource: "https://mapcarta.com/W552135649",
    category: "amusement-park",
    tags: ["artificial-worlds","architectures-of-prosperity","themed-environment","leisure","tourism","speculative-futures"],
    program: "Dutch-themed urban environment with canals, hotels, recreation, restaurants, shops and landscaping",
    condition: "Operating leisure destination; adaptations and later additions have altered the original project.",
    description: "A purpose-built reconstruction of an imagined Dutch city in Kyushu, conceived as a complete inhabitable leisure world. Its construction materialized an elaborate economic and cultural vision of the early 1990s.",
    source: "https://english.huistenbosch.co.jp/aboutus/sdgs/history.html",
    dateNote: "Site works began in 1988, buildings completed January 1992, public opening 25 March 1992."
  },
  {
    id: "la-grande-motte",
    name: "La Grande-Motte",
    city: "La Grande-Motte",
    country: "France",
    year: "1965 (initial site works)",
    clockYear: 1965,
    clockEvent: "Resort construction began",
    coordinates: [4.085833,43.561389],
    coordinateSource: "https://www.lagrandemotte.fr/histoire-de-la-grande-motte/",
    category: "new-town",
    tags: ["architectures-of-prosperity","artificial-worlds","masterplanning","mass-tourism","leisure","public-space","urban-experiment","ordinary-heritage"],
    program: "Planned coastal resort, housing, hotels, public spaces, shops, marina and leisure",
    condition: "Living town developed in phases. The 1965 date denotes initial site and harbor works, not the completion of the entire resort.",
    description: "Jean Balladur's planned seaside town, with sculptural pyramidal housing and landscaped public spaces designed around a modern collective ideal of coastal leisure.",
    source: "https://lagrandemotte-architecture.com/construction-les-dates-cles/",
    dateNote: "Site works began in 1965, first foundation stone laid in 1967, first pyramid residences delivered in 1968."
  },
  {
    id: "seonyudo-park",
    name: "Seonyudo Park",
    city: "Seoul",
    country: "South Korea",
    year: "2002 (park opened)",
    clockYear: 2002,
    clockEvent: "Industrial site became a park",
    coordinates: [126.89969,37.54346],
    coordinateSource: "https://mapcarta.com/33186136",
    category: "public-park",
    tags: ["afterlives","adaptive-reuse","industrial-memory","water-infrastructure","ordinary-heritage","adaptive-landscape","urban-memory","public-space"],
    program: "Ecological park, gardens, paths and reuse of former water treatment infrastructure",
    condition: "Existing public park preserving parts of the former purification plant. The 2002 date refers to conversion and public opening, not the original plant's construction.",
    description: "Former water purification infrastructure transformed into an island park on the Han River. Concrete technical structures survive as gardens and spatial memory.",
    source: "https://english.seoul.go.kr/seonyudo-park-in-seoul/",
    dateNote: "The site reopened as Seonyudo Park in 2002; earlier industrial structures predate the park."
  },
  {
    id: "sewoon-sangga",
    name: "Sewoon Sangga",
    city: "Seoul",
    country: "South Korea",
    year: "1968 (completed)",
    clockYear: 1968,
    clockEvent: "Megastructure completed",
    coordinates: [126.9930403,37.5693263],
    coordinateSource: "https://archives.seoul.go.kr/authority/GEOL-00581",
    category: "mixed-use-complex",
    tags: ["architectures-of-prosperity","afterlives","ordinary-heritage","electronics","mixed-program","urban-memory","commercial-obsolescence","adaptive-reuse"],
    program: "Linear megastructure with residences, electronic retail, workshops and pedestrian circulation",
    condition: "Still in use in a changing urban district. Proposals for redevelopment and renewal should be evaluated by phase, rather than assuming the whole complex is abandoned.",
    description: "A landmark mixed-use megastructure that once embodied Korean technological modernity. Its changing network of electronics, crafts and housing reveals tensions between lived continuity and redevelopment.",
    source: "https://archives.seoul.go.kr/authority/GEOL-00581",
    dateNote: "Seoul Archives identifies 1968 as the completion of the original megastructure."
  },
  {
    id: "espaces-abraxas",
    name: "Les Espaces d'Abraxas",
    city: "Noisy-le-Grand",
    country: "France",
    year: "1983 (inaugurated)",
    clockYear: 1983,
    clockEvent: "Housing ensemble inaugurated",
    coordinates: [2.54306,48.84028],
    coordinateSource: "https://www.wikidata.org/wiki/Q3058350",
    category: "residential-complex",
    tags: ["postmodernism","architectures-of-prosperity","ordinary-heritage","residential","urban-memory","artificial-worlds","public-space"],
    program: "Postmodern housing ensemble and monumental shared exterior spaces",
    condition: "Inhabited residential complex. The building's visual notoriety should not eclipse residents' everyday lives and social memory.",
    description: "Ricardo Bofill's monumental housing ensemble, designed as a theatrical urban composition. Its cinematic image contrasts with its continuing identity as lived residential heritage.",
    source: "https://www.wikidata.org/wiki/Q3058350",
    dateNote: "Construction between 1978 and 1983, with inauguration in 1983."
  },
  {
    id: "avoriaz",
    name: "Avoriaz 1800",
    city: "Morzine",
    country: "France",
    year: "1966 (first hotel opened)",
    clockYear: 1966,
    clockEvent: "First hotel opened",
    coordinates: [6.77029,46.19254],
    coordinateSource: "https://mapcarta.com/18416974",
    category: "leisure-resort",
    tags: ["architectures-of-prosperity","artificial-worlds","masterplanning","mass-tourism","leisure","ordinary-heritage","tourism","adaptive-landscape"],
    program: "Car-free mountain resort, hotels, holiday residences, ski infrastructure and public spaces",
    condition: "Operating mountain resort built and expanded in phases. The first hotel opened for Christmas 1966.",
    description: "A car-free, ski-in ski-out resort conceived through organic alpine architecture. Its circulation, interiors and landscape stage an alternative modern holiday environment.",
    source: "https://www.avoriaz.com/decouvrir/la-station/architecture-organique/",
    dateNote: "Hôtel des Dromonts opened at Christmas 1966. The resort's buildings were developed over subsequent decades."
  },
  {
    id: "kai-tak-cruise-terminal",
    name: "Kai Tak Cruise Terminal",
    city: "Hong Kong",
    country: "Hong Kong",
    year: "2013 (opened)",
    clockYear: 2013,
    clockEvent: "Cruise terminal opened",
    coordinates: [114.216944,22.303611],
    coordinateSource: "https://www.wikidata.org/wiki/Q3531700",
    category: "transport-infrastructure",
    tags: ["afterlives","infrastructure","adaptive-reuse","tourism","public-space","artificial-worlds","urban-memory"],
    program: "Cruise terminal, port infrastructure, public roof park, passenger facilities and event spaces",
    condition: "Operating terminal on the former airport runway. The 2013 date refers to commissioning of the new terminal, not the construction of Kai Tak Airport.",
    description: "A maritime passenger terminal built on the tip of the former Kai Tak Airport runway, extending the infrastructure's identity from air travel to ocean tourism.",
    source: "https://www.tourism.gov.hk/en/tourism-projects.php?project=kai_tak_cruise_terminal",
    dateNote: "Construction began in 2010 and the first berth and terminal building entered service in June 2013."
  },
  {
    id: "921-earthquake-museum",
    name: "921 Earthquake Museum of Taiwan",
    city: "Wufeng, Taichung",
    country: "Taiwan",
    year: "2001 (museum established)",
    clockYear: 2001,
    clockEvent: "Museum established",
    coordinates: [120.69962,24.04226],
    coordinateSource: "https://eng.taiwan.net.tw/m1.aspx?id=a12-00013&print=1&sno=0002112",
    category: "museum",
    tags: ["ordinary-heritage","memorial","historic-site","afterlives","urban-memory","heritage-conservation","adaptive-reuse"],
    program: "Museum, preserved earthquake-damaged school structures, seismic fault exhibits and memorial landscape",
    condition: "Museum preserving the damaged school site of the 1999 earthquake. The museum developed in phases through 2007, distinct from the 1999 disaster.",
    description: "A damaged school and disrupted ground preserved as a public memorial and museum. Here, conservation turns the material trace of a rupture into collective memory and education.",
    source: "https://www.nmns.edu.tw/en/visit/explore-our-parks/park_921/",
    dateNote: "Earthquake in September 1999; museum officially named and established in 2001; development completed in stages."
  },
  {
    id: "sanzhi-ufo-houses",
    name: "Sanzhi UFO Houses (demolished)",
    city: "Sanzhi, New Taipei",
    country: "Taiwan",
    year: "1978 (construction began; demolished 2010)",
    clockYear: 1978,
    clockEvent: "Construction began, site now demolished",
    coordinates: [121.4775,25.26083],
    coordinateSource: "https://www.wikidata.org/wiki/Q704502",
    category: "leisure-resort",
    tags: ["artificial-worlds","suspended-time","afterlives","demolished","historic-site","vacation-housing","speculative-futures","tourism"],
    program: "Unfinished coastal holiday development with prefabricated pod-shaped structures",
    condition: "Demolished. Construction began in 1978, stalled around 1980 and the remaining structures were demolished by 2010. This point denotes the historical location only.",
    description: "A never-completed futuristic coastal holiday village of capsule-like homes. Its disappearance makes the site an archival investigation rather than a contemporary architecture visit.",
    source: "https://www.wikidata.org/wiki/Q704502",
    dateNote: "Construction started in 1978. Structures were demolished between 2008 and 2010. Coordinates refer to the former site."
  }
];

export function categoryLabel(id) {
  return CATEGORIES.find(category => category.id === id)?.label || "Uncategorised";
}
export function tagLabel(id) {
  return TAG_LABELS[id] || String(id).replaceAll("-", " ").replace(/\b\w/g, char => char.toUpperCase());
}
export function matchesFilters(place, category, selectedTags, searchTerm = "") {
  const categoryMatch = category === "all" || place.category === category;
  const tags = Array.isArray(place.tags) ? place.tags : [];
  const tagsMatch = selectedTags.every(tag => tags.includes(tag));
  const haystack = [
    place.name, place.city, place.country, place.description,
    place.program,place.condition,place.locationNote,
    ...(Array.isArray(place.searchTerms) ? place.searchTerms : [])
  ].filter(Boolean).join(" ").toLowerCase();
  return categoryMatch && tagsMatch && haystack.includes(searchTerm.trim().toLowerCase());
}
