/**
 * ARTIFICE / ATLAS — EDIT THE RESEARCH INVENTORY HERE.
 *
 * Place IDs must stay unique. WGS84 coordinates are always [longitude, latitude].
 * "condition" preserves provisional notes from Yasmine's research table; these are
 * NOT independently verified current closure or demolition announcements.
 * "coordinateSource" documents where an actual location was checked.
 * "locationNote" flags provisional matches when the table names a district rather
 * than a single identifiable building.
 * Upload your own photographs to assets/places/<id>/, then add filenames to images.
 */

export const CATEGORIES = [
  { id: "shopping-mall", label: "Shopping mall" },
  { id: "department-store", label: "Department store" },
  { id: "cinema-complex", label: "Cinema complex" },
  { id: "amusement-park", label: "Amusement park" },
  { id: "electronics-complex", label: "Electronics complex" },
  { id: "mixed-use-complex", label: "Mixed-use complex" },
  { id: "new-town", label: "New town" },
  { id: "hotel", label: "Hotel" },
  { id: "airport", label: "Airport" },
  { id: "car-park", label: "Car park" },
  { id: "residential-complex", label: "Residential complex" },
  { id: "other", label: "Other" }
];

export const TAG_LABELS = {
  "adaptive-reuse": "Adaptive reuse",
  "consumerism": "Consumerism",
  "electronics": "Electronics",
  "masterplanning": "Masterplanning",
  "periphery": "Periphery",
  "residential": "Residential",
  "retail": "Retail",
  "subculture": "Subculture",
  "technology": "Technology",
  "fashion": "Fashion",
  "commercial-decline": "Commercial decline",
  "mixed-program": "Mixed programme",
  "cultural-program": "Cultural programme",
  "transit-oriented": "Transit-oriented",
  "1970s": "1970s",
  "commercial-obsolescence": "Commercial obsolescence",
  "urban-memory": "Urban memory"
};

export const seedPlaces = [
  // FRANCE — existing places completed with the working inventory.
  {
    id: "maine-montparnasse",
    name: "Centre commercial Maine–Montparnasse",
    city: "Paris", country: "France",
    coordinates: [2.3211, 48.8423],
    category: "shopping-mall", tags: ["retail", "adaptive-reuse", "1970s"],

    description: "The Maine–Montparnasse retail complex is the site of ARTIFICE's La machine du dialogue project.",
    project: "projects.html?project=la-machine-du-dialogue",
    images: [
      { src: "assets/places/maine-montparnasse/01.webp", caption: "Existing interior passage", alt: "Interior of the Maine–Montparnasse shopping centre" },
      { src: "assets/places/maine-montparnasse/02.webp", caption: "Existing commercial interior", alt: "Vacant interior of the Maine–Montparnasse shopping centre" }
    ],
    year: "1973",
    program: "Shops, offices and public facilities",
    condition: "Yasmine field inventory (Oct 2026): Centre closed to the public in 2026 according to the field inventory; basement sports facilities remain in use.",
    areaReliability: "High",
    area: "35,500 m² shopping centre",
    areaSource: "https://www.drieat.ile-de-france.developpement-durable.gouv.fr/IMG/pdf/190123_mrae_avis_sur_projet_rehabilitation_et_extension_tour_montparnasse_75_delibere.pdf",
    areaNote: "Commercial centre only, not the entire Maine–Montparnasse complex",
  },
  {
    id: "le-millenaire",
    name: "Le Millénaire", city: "Aubervilliers", country: "France",
    coordinates: [2.382, 48.900],
    category: "shopping-mall", tags: ["retail", "periphery", "commercial-decline"],


    description: "Shopping-centre and office development in Aubervilliers on the northern edge of Paris.",
    year: "2011",
    program: "Shops and offices",
    condition: "Yasmine field inventory (Oct 2026): Field observation: severe retail decline and departed major franchises.",
    areaReliability: "Original",
    area: "56,000 m² retail; 17,000 m² offices",
  },
  {
    id: "bercy-2",
    name: "Bercy 2", city: "Charenton-le-Pont", country: "France",
    coordinates: [2.405, 48.823],
    category: "shopping-mall", tags: ["retail", "periphery", "commercial-decline"],


    description: "Shopping centre by Renzo Piano Building Workshop at the edge of Paris.",
    year: "1990",
    program: "Shops",
    condition: "Yasmine field inventory (Oct 2026): Field observation: partly repurposed upper floor; proposed redevelopment, potential demolition in 2031 not confirmed.",
    areaReliability: "Original",
    area: "36,000 m² retail",
  },
  {
    id: "la-vache-noire",
    name: "La Vache Noire", city: "Arcueil", country: "France",
    coordinates: [2.32885, 48.81135],
    coordinateSource: "https://mapcarta.com/W62643138",
    category: "shopping-mall", tags: ["retail", "periphery", "commercial-decline"],


    description: "Shopping centre in Arcueil with a publicly accessible rooftop landscape.",
    year: "2007",
    program: "Shops",
    condition: "Yasmine field inventory (Oct 2026): Field observation: gradual commercial decline and vacant units.",
    areaReliability: "Original",
    area: "49,263 m²",
  },
  {
    id: "belle-epine",
    name: "Belle Épine", city: "Thiais", country: "France",
    coordinates: [2.37214, 48.75659],
    coordinateSource: "https://mapcarta.com/W263891555",
    category: "shopping-mall", tags: ["retail", "periphery", "1970s"],


    description: "A major early regional shopping centre in Thiais, southeast of Paris.",
    year: "1971",
    program: "Shops and cinema",
    condition: "Yasmine field inventory (Oct 2026): Field observation: renewed activity associated with transport and projects in surrounding area.",
    areaReliability: "Original",
    area: "140,000 m²",
  },

  // ALGERIA
  {
    id: "riadh-el-feth",
    name: "Riadh El Feth", city: "Algiers", country: "Algeria",
    coordinates: [3.07025, 36.74326],
    coordinateSource: "https://mapcarta.com/fr/W1271733343",
    category: "mixed-use-complex", tags: ["retail", "cultural-program", "mixed-program"],

    description: "Post-independence commercial and cultural complex at El Madania, inaugurated in the mid-1980s.",
    year: "1982 (construction began)",
    program: "Shops, cultural facilities and leisure",
    condition: "Yasmine field inventory (Oct 2026): Field observation: largely underused commercial and cultural complex.",
    areaReliability: "Pending",
  },

  // SOUTH KOREA
  {
    id: "techno-mart",
    name: "Gangbyeon Techno Mart", city: "Seoul", country: "South Korea",
    coordinates: [127.0957, 37.5355],
    category: "electronics-complex", tags: ["retail", "electronics", "technology"],

    description: "Large electronics and entertainment retail complex near Gangbyeon Station.",
    year: "1998",
    program: "Electronics retail, shops, cinema and offices",
    condition: "Yasmine field inventory (Oct 2026): Field observation: vacant shops, informal retail appearance and reuse of two floors for weddings.",
    areaReliability: "High",
    area: "≈260,000 m² total GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20110705141100004",
    areaNote: "Total GFA includes offices and other facilities",
    images: [{"src":"assets/places/techno-mart/DSC01729.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01735.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01766.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01776.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"},{"src":"assets/places/techno-mart/DSC01780.JPG","caption":"Gangbyeon Techno Mart","alt":"Documentary photograph of Gangbyeon Techno Mart"}],
  },
  {
    id: "venezia-mega-mall",
    name: "Venezia Mega Mall", city: "Seoul", country: "South Korea",
    coordinates: [127.021434, 37.570978],
    coordinateSource: "https://lse.purpleo.kr/article/1415",
    locationNote: "Approximately located from a commercial registry at 400 Cheonggyecheon-ro. Building footprint should be checked.",
    category: "shopping-mall", tags: ["retail", "mixed-program"],
    description: "Shopping complex at 400 Cheonggyecheon-ro, Hwanghak-dong, Seoul.",
    year: "2008",
    program: "Shopping and leisure within residential complex",
    condition: "Yasmine field inventory (Oct 2026): Field observation: space mostly used for online retail trade, with underused upper levels.",
    areaReliability: "High",
    area: "≈130,000 m² mall GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20110614058700003",
    areaNote: "Retail and leisure areas, not residential towers",
  },
  {
    id: "migliore-dongdaemun",
    name: "Migliore Dongdaemun", city: "Seoul", country: "South Korea",
    coordinates: [127.008527, 37.567963],
    coordinateSource: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?menuSn=315&vcontsId=106366",
    locationNote: "The inventory says 'Migliore'. This pin identifies the Dongdaemun branch; confirm it is the intended one.",
    category: "shopping-mall", tags: ["retail", "fashion"],
    description: "Multi-storey fashion retail complex in the Dongdaemun district.",
    year: "1998",
    program: "Vertical fashion retail",
    condition: "Yasmine field inventory (Oct 2026): Field observation: some vacant floors and declining commercial activity.",
    areaReliability: "Medium",
    area: "49,566 m² total GFA",
    areaSource: "https://disco.re/l/ozcxwk",
    areaNote: "Whole building GFA",
  },
  {
    id: "apm-place",
    name: "apM PLACE", city: "Seoul", country: "South Korea",
    coordinates: [127.00841, 37.5653],
    coordinateSource: "https://mapcarta.com/W400847801",
    category: "shopping-mall", tags: ["retail", "fashion"],
    description: "Multi-storey fashion wholesale and shopping complex at Eulji-ro 276, Dongdaemun.",
    year: "2016",
    program: "Wholesale fashion and vertical retail",
    condition: "Yasmine field inventory (Oct 2026): Field observation: vacancies in a wholesale centre.",
    areaReliability: "Pending",
  },
  {
    id: "hapjeong-mall",
    name: "Hapjeong Mall / Mecenatpolis (provisional)", city: "Seoul", country: "South Korea",
    coordinates: [126.91378, 37.55089],
    coordinateSource: "https://mapcarta.com/W306956698",
    locationNote: "The inventory only says 'Hapjeong mall'. Mapped provisionally to Mecenatpolis; please confirm the intended building.",
    category: "shopping-mall", tags: ["retail", "mixed-program", "transit-oriented"],
    description: "Shopping and mixed-use complex at Hapjeong Station, provisionally identified with Mecenatpolis.",
    year: "2012",
    program: "Shopping within residential complex",
    condition: "Yasmine field inventory (Oct 2026): Field observation: active centre with vacant basement and upper-floor units.",
    areaReliability: "High",
    area: "40,176 m² mall GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20120312093300003",
    areaNote: "Mall only, excluding residential towers",
  },
  {
    id: "goodmorning-city",
    name: "Goodmorning City", city: "Seoul", country: "South Korea",
    coordinates: [127.0075, 37.56668],
    coordinateSource: "https://mapcarta.com/W358284628",
    category: "shopping-mall", tags: ["retail", "fashion"],
    description: "Multi-storey commercial complex in Seoul's Dongdaemun district.",
    year: "2008",
    program: "Fashion retail and leisure facilities",
    condition: "Yasmine field inventory (Oct 2026): Field observation: spa open, cinema reportedly closed September 2026, multiple vacancies.",
    areaReliability: "High",
    area: "92,206 m² total GFA",
    areaSource: "https://m.apparelnews.co.kr/news/news_view/?idx=130709",
    areaNote: "Includes commercial, leisure and office floors",
  },
  {
    id: "wangsimni-bitplex",
    name: "Wangsimni / Bitplex (provisional)", city: "Seoul", country: "South Korea",
    coordinates: [127.0383, 37.56212],
    coordinateSource: "https://mapcarta.com/W1258207418",
    locationNote: "The inventory only says 'Wangsimni'. Mapped provisionally to the Bitplex / Enter-6 complex at Wangsimni Station.",
    category: "mixed-use-complex", tags: ["retail", "mixed-program", "transit-oriented"],
    description: "Shopping and entertainment complex integrated with Wangsimni Station.",
    year: "2008",
    program: "Rail station, shops, cinema and leisure",
    condition: "Yasmine field inventory (Oct 2026): Field observation: active station-linked centre with less-used aisles.",
    areaReliability: "High",
    area: "≈99,000 m² total GFA",
    areaSource: "https://fi.co.kr/mobile/view.asp?idx=40956",
    areaNote: "Station and mixed-use complex",
  },

  // FOUR ADDITIONAL SITES IN JAPAN, SOUTH KOREA, HONG KONG AND TAIWAN.
  {
    id: "aeon-sanda-woody-town",
    name: "AEON Sanda Woody Town",
    city: "Sanda", country: "Japan",
    coordinates: [135.18746, 34.90853],
    coordinateSource: "https://mapcarta.com/W506631400",
    category: "shopping-mall",
    tags: ["retail", "cultural-program"],

    description: "Shopping complex in Sanda Woody Town, Hyogo Prefecture, with a multi-screen cinema. It forms part of the commercial centre of a planned suburban community.",
    year: "2000",
    program: "Shops, cinema and suburban centre",
    condition: "Yasmine field inventory (Oct 2026): Former Saty shopping centre.",
    areaReliability: "High",
    area: "25,298 m² retail",
    areaSource: "https://www.jcsc.or.jp/data/pdf/2019list_of_shopping_centers.pdf",
    areaNote: "Retail area only",
  },
  {
    id: "time-terrace-dongtan",
    name: "Time Terrace Dongtan",
    city: "Hwaseong", country: "South Korea",
    coordinates: [127.069312, 37.204856],
    coordinateSource: "https://bim.purpleo.kr/article/1297",
    locationNote: "Interpreted from 'Times Square in Dongtan'. This is the Time Terrace mall inside Metapolis, operated by the company behind Seoul Times Square. It is not the unrelated SH Times Square industrial building.",
    category: "shopping-mall",
    tags: ["retail", "consumerism", "mixed-program", "commercial-obsolescence"],

    description: "Shopping centre within Dongtan's Metapolis residential and commercial complex. Formerly Center Point Mall, the retail spaces were relaunched as Time Terrace in 2022.",
    source: "https://view.asiae.co.kr/en/article/2022031709305224800",
    year: "2022 (renovation)",
    program: "Shops, cinema and restaurants",
    condition: "Yasmine field inventory (Oct 2026): Former Center Point Mall, relaunched as Time Terrace in 2022.",
    areaReliability: "High",
    area: "≈142,000 m² total GFA",
    areaSource: "https://www.yna.co.kr/view/AKR20220317039800003",
    areaNote: "Commercial blocks A and B",
  },
  {
    id: "moko-mong-kok-east",
    name: "MOKO (Grand Century Place)",
    city: "Hong Kong", country: "Hong Kong",
    coordinates: [114.17238, 22.32318],
    coordinateSource: "https://mapcarta.com/W37517528",
    locationNote: "Interpreted from 'Mong Kok East'. This is MOKO, the shopping mall beside Mong Kok East station.",
    category: "shopping-mall",
    tags: ["retail", "mixed-program", "transit-oriented"],

    description: "Multi-level shopping complex connected to Mong Kok East station, integrated with offices and the Royal Plaza Hotel.",
    source: "https://www.wikidata.org/wiki/Q11080935",
    year: "1997",
    program: "Shops, hotel, offices and station access",
    condition: "Yasmine field inventory (Oct 2026): Shopping complex linked to Mong Kok East.",
    areaReliability: "Medium",
    area: "≈67,000 m² retail GFA",
    areaSource: "https://www.luxstate.com/hk-retail/mall/kowloon/moko/",
    areaNote: "Mall only",
  },
  {
    id: "qianyue-building",
    name: "Qianyue Building (千越大樓)",
    city: "Taichung", country: "Taiwan",
    coordinates: [120.68314, 24.13827],
    coordinateSource: "https://explander.com/east-central-asia/taiwan/taichung/qianyue-building-taichung-taiwan/",
    category: "mixed-use-complex",
    tags: ["retail", "commercial-obsolescence", "urban-memory", "adaptive-reuse", "1970s"],

    description: "An ageing mixed-use commercial building near Taichung Station, known for its former rooftop restaurant and its partial reuse by artists during the Escape Plan X initiative.",
    source: "https://www.taipeitimes.com/News/feat/archives/2025/05/13/2003836777",
    year: "1970s",
    program: "Former department store, restaurants, bars and housing",
    condition: "Yasmine field inventory (Oct 2026): Field observation: former retail space marked by fire in 2005 and artist interventions.",
    areaReliability: "Medium",
    area: "21,070 m² total GFA",
    areaSource: "https://taichung2050.pixnet.net/blog/posts/10342072765",
    areaNote: "Building GFA",
  },

  // ADDITIONAL ARTIFICE RESEARCH PLACES (already on the Atlas; preserved)
  {
    id: "dongtan",
    name: "Dongtan New Town", city: "Hwaseong", country: "South Korea",
    coordinates: [127.071, 37.206],
    category: "new-town", tags: ["masterplanning", "consumerism", "residential"],
    description: "A planned new town whose apartment brands, infrastructure and corporate economies offer a lens onto contemporary urban consumption.",
    year: "2007 (phase 1)",
    program: "New town, housing and commerce",
    condition: "Yasmine field inventory (Oct 2026): Planned new town; area is land, not floor area.",
    areaReliability: "High",
    area: "9,035,000 m² development land (Dongtan 1)",
    areaSource: "https://www.molit.go.kr/USR/policyData/m_34681/dtl.jsp?id=524&lcmspage=29",
    areaNote: "Dongtan 1 development land, not building area",
  },
  {
    id: "nakano-broadway",
    name: "Nakano Broadway", city: "Tokyo", country: "Japan",
    coordinates: [139.6658, 35.7092],
    category: "mixed-use-complex", tags: ["retail", "subculture"],
    description: "A multi-storey shopping complex that evolved into a dense ecosystem of specialist retail and subcultures.",
    images: [{ src: "assets/places/nakano-broadway/DSC01831.JPG", caption: "Nakano Broadway", alt: "Photograph of Nakano Broadway" }],
    year: "1966",
    program: "Shops, apartments and specialist retailers",
    condition: "Yasmine field inventory (Oct 2026): Field observation: commercial gallery specialising increasingly in collectibles and subculture.",
    areaReliability: "Medium",
    area: "≈53,366 m² main building GFA",
    areaSource: "https://skyscraperclub.com/?p=16733",
    areaNote: "Main building only",
  },
  {
    id: "times-square-seoul",
    name: "Times Square Yeongdeungpo",
    city: "Seoul",
    country: "South Korea",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, hotel, cinema and offices",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "High",
    description: "Shops, hotel, cinema and offices in Seoul",
    area: "376,400 m² total GFA; 126,800 m² retail",
    areaSource: "https://www.hankyung.com/article/2009090366231",
    areaNote: "Mixed-use GFA includes non-retail area",
  },
  {
    id: "art-forest",
    name: "Art Forest",
    city: "Seoul",
    country: "South Korea",
    coordinates: null,
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and leisure",
    condition: "Yasmine field inventory (Oct 2026): New retail facility reported with vacant ground-floor units; exact location requires verification",
    areaReliability: "Pending",
    description: "Shops and leisure in Seoul"
  },
  {
    id: "euljiro-underground",
    name: "Euljiro Underground Shopping Centre",
    city: "Seoul",
    country: "South Korea",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Underground shops and pedestrian passageways",
    condition: "Yasmine field inventory (Oct 2026): Field observation: underused underground commercial arcade",
    areaReliability: "High",
    description: "Underground shops and pedestrian passageways in Seoul",
    area: "20,334 m² arcade",
    areaSource: "https://www.sisul.or.kr/global/main/en/sub/shoppingcenter.jsp",
    areaNote: "Underground arcade, not adjacent centres",
  },
  {
    id: "lions-plaza",
    name: "Lions’ Plaza Commercial Building",
    city: "Taipei",
    country: "Taiwan",
    coordinates: null,
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and mixed-use spaces",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "Pending",
    description: "Shops and mixed-use spaces in Taipei"
  },
  {
    id: "sanchong-tang-city",
    name: "Sanchong Tang City Plaza",
    city: "New Taipei",
    country: "Taiwan",
    coordinates: null,
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and mixed-use spaces",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited; shopping centre coordinates require verification",
    areaReliability: "Pending",
    description: "Shops and mixed-use spaces in New Taipei"
  },
  {
    id: "new-shimbashi-building",
    name: "New Shimbashi Building",
    city: "Tokyo",
    country: "Japan",
    coordinates: [139.75736,35.66628],
    category: "mixed-use-complex",
    tags: ["retail"],
    program: "Shops and offices",
    condition: "Yasmine field inventory (Oct 2026): Field observation: decline apparent on upper floors",
    areaReliability: "High",
    description: "Shops and offices in Tokyo",
    area: "58,107 m² total GFA",
    areaSource: "https://www.mhs.co.jp/work/new-shinbashi/",
    areaNote: "Whole building GFA",
  },
  {
    id: "asakusa-underground",
    name: "Asakusa Underground Shopping Street",
    city: "Tokyo",
    country: "Japan",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Underground shops and restaurants",
    condition: "Yasmine field inventory (Oct 2026): Established historic arcade, now visited for its retro character",
    areaReliability: "Pending",
    description: "Underground shops and restaurants in Tokyo"
  },
  {
    id: "aeon-laketown",
    name: "AEON LakeTown",
    city: "Koshigaya",
    country: "Japan",
    coordinates: [139.82611,35.87861],
    category: "shopping-mall",
    tags: ["retail"],
    program: "Large suburban shopping centre",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "High",
    description: "Large suburban shopping centre in Koshigaya",
    area: "≈403,000 m² total GFA; 190,000 m² leasable",
    areaSource: "https://www.aeonmall.com/news/index/13594/",
    areaNote: "Three Aeon complexes combined",
  },
  {
    id: "aeon-makuhari-new-city",
    name: "AEON MALL Makuhari New City",
    city: "Chiba",
    country: "Japan",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Large interconnected shopping centre",
    condition: "Yasmine field inventory (Oct 2026): Field observation: oversized facilities and areas with low use",
    areaReliability: "High",
    description: "Large interconnected shopping centre in Chiba",
    area: "≈402,000 m² total GFA; 128,000 m² leasable",
    areaSource: "https://www.aeonmall.com/facility/detail/1529/",
    areaNote: "GFA includes parking",
  },
  {
    id: "hatoya-hotel",
    name: "Hatoya Hotel",
    city: "Ito",
    country: "Japan",
    coordinates: null,
    category: "hotel",
    tags: ["retail"],
    program: "Hot spring hotel and leisure facilities",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "Pending",
    description: "Hot spring hotel and leisure facilities in Ito"
  },
  {
    id: "decks-tokyo-beach",
    name: "DECKS Tokyo Beach",
    city: "Tokyo",
    country: "Japan",
    coordinates: [139.7759,35.62906],
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, attractions and leisure",
    condition: "Yasmine field inventory (Oct 2026): Field observation: underused areas; Island Mall added 2000",
    areaReliability: "High",
    description: "Shops, attractions and leisure in Tokyo",
    area: "≈69,035 m² total GFA",
    areaSource: "https://www.tokyu-land.co.jp/urban/shopping/list/051.html",
    areaNote: "Total GFA",
  },
  {
    id: "divercity-tokyo-plaza",
    name: "DiverCity Tokyo Plaza",
    city: "Tokyo",
    country: "Japan",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, restaurants and attractions",
    condition: "Yasmine field inventory (Oct 2026): Field observation: several large low-use areas",
    areaReliability: "High",
    description: "Shops, restaurants and attractions in Tokyo",
    area: "≈140,200 m² mall and parking GFA; 47,000 m² retail",
    areaSource: "https://www.mitsuifudosan.co.jp/corporate/news/2021/0412/",
    areaNote: "Mall and parking area",
  },
  {
    id: "aquacity-odaiba",
    name: "AQUA CiTY ODAIBA",
    city: "Tokyo",
    country: "Japan",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "Shops, restaurants and cinema",
    condition: "Yasmine field inventory (Oct 2026): Not yet visited",
    areaReliability: "High",
    description: "Shops, restaurants and cinema in Tokyo",
    area: "≈94,000 m² total GFA; 42,500 m² retail",
    areaSource: "https://www.mec.co.jp/ir/library/2013/4Q/FACT%20BOOK%20201303.pdf",
    areaNote: "Mall GFA and retail area",
  },
  {
    id: "rakuseinu",
    name: "Rakuseinu / Rakusai Town Centre",
    city: "Kyoto",
    country: "Japan",
    coordinates: null,
    category: "shopping-mall",
    tags: ["retail"],
    program: "New-town shopping arcade",
    condition: "Yasmine field inventory (Oct 2026): Field observation: ongoing reuse and vacant upper floor after adjoining store closure",
    areaReliability: "Medium",
    description: "New-town shopping arcade in Kyoto",
    area: "15,915 m² retail",
    areaSource: "https://toshoken.com/news/30550",
    areaNote: "Shopping arcade, not adjacent department store",
  },
  {
    id: "viking-line",
    name: "Viking Line Baltic Ferry",
    city: "Baltic Sea",
    country: "Multiple countries",
    coordinates: null,
    category: "other",
    tags: ["retail"],
    program: "Passenger ferry, retail and leisure",
    condition: "Yasmine field inventory (Oct 2026): Helsinki, Tallinn and Stockholm ferry routes; specify a vessel before geolocating",
    areaReliability: "Pending",
    description: "Passenger ferry, retail and leisure in Baltic Sea"
  },
];

export function categoryLabel(id) {
  return CATEGORIES.find(category => category.id === id)?.label || "Uncategorised";
}
export function tagLabel(id) {
  return TAG_LABELS[id] || String(id).replaceAll("-", " ").replace(/\b\w/g, char => char.toUpperCase());
}
export function matchesFilters(place, category, selectedTags, searchTerm = "") {
  const categoryMatch = category === "all" || place.category === category;
  const tags = Array.isArray(place.tags) ? place.tags : [];
  const tagsMatch = selectedTags.every(tag => tags.includes(tag));
  const haystack = [
    place.name, place.city, place.country, place.description,
    place.program,place.condition,place.locationNote
  ].filter(Boolean).join(" ").toLowerCase();
  return categoryMatch && tagsMatch && haystack.includes(searchTerm.trim().toLowerCase());
}
